apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cert-manager-webhook-duckdns
  namespace: cert-manager
spec:
  interval: 5m0s
  url: https://github.com/joshuakraitberg/cert-manager-webhook-duckdns
  ref:
    branch: master
  ignore: |
    # exclude all
    /*
    # include charts directory
    !/charts/
