apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  settings.yaml: |
    title: Homelab
    useEqualHeights: true
    headerStyle: boxedWidgets
    language: pt
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: false
      showSearchSuggestions: true
      hideVisitURL: true
    hideVersion: true
    showStats: true
    layout:
      Media:
        style: row
        columns: 4
      Management:
        style: row
        columns: 4
  bookmarks.yaml: ""
  services.yaml: ""
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        uptime: true
        units: metric
    - search:
        provider: google
        target: _blank
    - openmeteo:
        label: São Carlos
        latitude: -22.0154
        longitude: -47.8911
        cache: 5
        units: metric
  kubernetes.yaml: |
    mode: cluster
  custom.css: ""
  custom.js: ""
  docker.yaml: ""
