apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    title: Home server
    quicklaunch:
      searchDescriptions: true
      hideInternetSearch: false
      hideVisitURL: true
    hideVersion: true
    showStats: true
    statusStyle: "dot"
    layout:
      Media:
        style: columns
      Management:
        style: columns
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Media:
        - Jellyfin:
            icon: jellyfin.png
            href: https://jellyfin.totorinho.duckdns.org
            description: Media server.
        - Sonarr:
            icon: sonarr.png
            href: https://sonarr.totorinho.duckdns.org
            description: TV Shows management
        - Radarr:
            icon: radarr.png
            href: https://radarr.totorinho.duckdns.org
            description: Movie management
        - Bazarr:
            icon: bazarr.png
            href: https://bazarr.totorinho.duckdns.org
            description: Subtitles management
        - Readarr:
            icon: readarr.png
            href: https://readarr.totorinho.duckdns.org
            description: Books management
        - Prowlarr:
            icon: prowlarr.png
            href: https://prowlarr.totorinho.duckdns.org
            description: Indexers management
        - qBittorrent:
            icon: qbittorrent.png
            href: https://qbittorrent.totorinho.duckdns.org
            description: Torrent client
    - Management:
        - Grafana:
            icon: grafana.png
            href: https://grafana.totorinho.duckdns.org
            description: Application monitoring
        - Flux:
            icon: flux-cd.png
            href: https://weave.totorinho.duckdns.org
            description: GitOps UI
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        uptime: true
        units: metric
    - search:
        provider: google
        target: _blank
    - openmeteo:
        label: São Carlos
        latitude: 22.0028
        longitude: 47.8970
        cache: 5
        units: metric
  docker.yaml: ""
