#+title:Homelab

My Homelab setup running as a [[https://k3s.io/][K3S]] cluster.

* Goals
- GitOps: everything should be deployed and reproducible with Flux
- Secrets should be safely stored in the repository
- SSL certificates for all services
- Monitoring stack with Prometheus and Grafana

* Repository structure
The repository structure follows the Flux recommendations, but I've also added an extra layer to provide a better separation of concerns. The idea is to have the following dependency graph

#+begin_example
              ┌───►Apps
              │
              │
Infrastructure│
              │
              │
              └───►Core Services
#+end_example

Infrastructure contains controllers and its configurations that do not expose any external services. They provide the fundamental resources to other services such as SSL certificates, secrets management, storage and so on.

Core services are composed of the administrative services exposed from the cluster. This includes any administrative dashboards and monitoring stacks.

Apps are the user-facing services provided by the cluster.

* TODO
- [X] GitOps setup with Flux
- [X] Secrets management
- [X] Manifests validation in CI
- [X] Ensure bootstrap order is correct
- [X] SSL certificates
- [X] Flux UI
- [X] Secrets replication for certificates
- [X] SSL certificate prod
- [X] Monitoring stack
- [X] Structure the repository
- [ ] Persist Prometheus data
- [ ] Strava dashboards in Grafana
- [ ] Provision Grafana dashboards and datasources
- [ ] Figure out how to do storage
- [ ] Jellyfin deploy
