apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: v58.x
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
  interval: 1h0m0s
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    grafana:
      defaultDashboardsTimezone: browser
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.totorinho.duckdns.org
        tls:
          - secretName: duckdns-wildcard-cert-totorinho.duckdns.org
            hosts:
              - grafana.totorinho.duckdns.org
