apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  chart:
    spec:
      chart: kube-prometheus-stack
      version: v58.x
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
  interval: 1h0m0s
  releaseName: kube-prometheus-stack
  targetNamespace: monitoring
  values:
    grafana:
      defaultDashboardsTimezone: browser
      defaultDashboardsEditable: false
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - grafana.totorinho.duckdns.org
        tls:
          - secretName: duckdns-wildcard-cert-totorinho.duckdns.org
            hosts:
              - grafana.totorinho.duckdns.org
      persistence:
        enabled: true
        type: pvc
        accessModes:
          - ReadWriteOnce
        size: 10Gi
      plugins:
        - grafana-strava-datasource
      # envFromSecret: grafana-env-secret
      grafana.ini:
        security:
          angular_support_enabled: false
        auth:
          generic_oauth:
            name: Strava
            icon: signin
            enabled: true
            allow_sign_up: true
            client_id: ${APP_CLIENT_ID}
            client_secret: ${APP_CLIENT_SECRET}
            scopes: activity:read_all
            email_attribute_path: username
            login_attribute_path: username
            name_attribute_path: join(' ', [firstname, lastname])
            auth_url: https://www.strava.com/oauth/authorize
            token_url: https://www.strava.com/api/v3/oauth/token
            api_url: https://www.strava.com/api/v3/athlete
    prometheus:
      prometheusSpec:
        retention: 24w
        storageSpec:
          volumeClaimTemplate:
            spec:
              storageClassName: local-path
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
