apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: cert-manager
      version: v1.14.x
      sourceRef:
        kind: HelmRepository
        name: jetstack
  interval: 1h0m0s
  releaseName: cert-manager
  targetNamespace: cert-manager
  values:
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "9.9.9.9"
    serviceAccount:
      create: true
      name: "cert-manager"
