apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
      version: 27.x
  interval: 1h0m0s
  timeout: 5m
  releaseName: traefik
  targetNamespace: traefik
  valuesFrom:
    - kind: ConfigMap
      name: traefik-helm-chart-value-overrides
      valuesKey: values.yaml
