apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-helm-chart-value-overrides
  namespace: traefik
data:
  values.yaml: |-
    globalArguments:
      - "--global.checknewversion=false"
      - "--global.sendanonymoususage=false"
    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
