apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: reflector
  namespace: reflector
spec:
  chart:
    spec:
      chart: reflector
      version: 7.1.x
      sourceRef:
        kind: HelmRepository
        name: reflector
  interval: 1h0m0s
  releaseName: reflector-controller
  targetNamespace: reflector
