{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "grafana-env-secret",
    "namespace": "monitoring",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "grafana-env-secret",
        "namespace": "monitoring",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "APP_CLIENT_ID": "AgBDApQ486sGJvf2byPlqk4xN8bcoKUkqvbwPYhRxnKQF5pLFRbRydijEuYf7lYpUHd2v8+6iHhyKmuenb39vuKu0OFAMHLsBix04+P9UK0EmR7DEF/xYxyEyXMOw4oJCbpaK8c1XPRH2JSoU0AatKybOCc/n1RfguVlgv9jXdKpixwk4Ovfe4Bo+IyVh+i+oeQGE06TCijkRJ9NCXjfVHs+D8laSiOc8f765to9qTKVuJYHeZ3IR+8ApWOEUxzaalr95oZdqOQsv94hT+mhM5oAOqtPgNUwnRwVKpe5gAxkHZn1wu0sZW/Lhf60BLG/IjFsenpkEb42UixLKO34cL/iCpsIxXgktOVBhc6Xdy7dhQSpTZRk2yV7UgUVX9SEsO+tJ/oKFhlxlurkx7L3TCSDJuiRLKfBxZb03+NzyVvvMilr36+8S4bYQl+QWqpkq0ZQ9pXjfmDN7Dj67Gd7QngNU3EUVvH7SuAljOb/0XIObGOdpS0oE3N4jecF5A1p7sVbV5Iwo22rAjByJq2bksyfWIYXxTjDsaSGKLcyq0UFJ9PJSR7zV9PExL5sPB2P9AE79G58P7hHyjSymal/6GS2o+T1b8nhzRZ3QaXC6ZmhtG54hBJ4lgK39fMrUPXHaCE2cmk7k+twpZH9J1z6yOw+I1GvI0uyaU63U0wjUnFrdil64SZEJOs+T0gLRbihozxAZAdagfI=",
      "APP_CLIENT_SECRET": "AgC+BVPo0NGi4rcBzmys+g+E/tZtJRmTTHzoJXXath43WoVT9Q2k7DS6eZetg07Iwf3H4V4yCKc3qxsXe8AoNWUIb+7rgtFcNXGE6n4N1qn3/dHffADIAR4RHK0w0sU07KQ3tGU1DiJxZlevEnjVy2OiEHALrdDH1yez3JxGx21/nR74eywDggVbJfdFORyAVhpxF4dx71ESP+s5R7VrDDG6qhZVFK418Oi97ktrKjWlpTRIyfLfK5F8C6GmLJYL8LmWYFdoDOgWjb8CVHfCgULqiZ0jJwosywNSnOirpiH9nq6wcLWgh8dPRPlOdjERtgvNTYtzZR4E8hrolm1t2QfazBqBt0QBRxAwJ9LKmwhbz6Pa/aO27PmZl7ITOti8Mn6t9Fiq1YgeV2uMLa5Dt9Mo7mmyIaqMfYrfTD6l2/mty4yH56fDXWWfu2KPxMszEcmAlqiaBwF2427/Zn7A6IQL/G3gQzPY51qqpsLgKfKFXpEm2ptKNG9Og2dN/RQo9NoaztFb/vvbyqLcrFT/3nXgbuoJff7brwptFmOKNWc3j7+hHvjnTsNygIDTbHTtVzsFjpOxbNUozXOqGlBDAMvnijhXrG7VGis9nvmQXvnCkEbnxudWS7LddughKqdQ6mcIwq1h3uGuPqelKp7Lk5nJsCdjgAr1d/K5ZSgVedmpf4nf5ZqojHZVkNaWhb8rC1mAaBGxqPIVMaGxExZaihDXapnt8F+V0Qf4jV7jZTUlSZqp8UT07+9j"
    }
  }
}
