---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCatgRl/0vDxQFYg+l8g9YlmeOtVzkuRQKCs7VfLue6lx5Whjc1ujXZdxuCZsbdqR7iX2n9C60uIovhEp8YQqYWCJPZbtRb21B7i87b57/HZSiaS2P989r8bs42imNczH8AJ7dwU+3bBXJoZe1C/zbqLX02LOHRQlpne/aklhHsnIp0k0EjKzFV438viAxtqrXrCknKFAK6JtVLuQpa9L0MS0Uthl9PiuyGAXgsO8+g+0OdLs5L9iZ5w1bPSq8O0F15GyAZUs5FYQ2r5o6waC7pVVINCtdzwYTrRfFdFMlHnXX6uahySbYW8CZywkqU0705ZLCcR9wa0kFW5JuMNIqgEhG+x6m85ndO72FBEHSyYIbb/crN4kzP0VGwQ1K4dO7WcBj//QQ0Yyg5nCDGeufxwwiQuNHoZWEhccuMm7rMVHWdj69IWdqM7YQoNJDmtyFdfbL8edDqNTIyPYwY9BgkPKpLb2PQJkgl2Lqmkwy2jzAkvFu6lr9YztS3MwUVolGWpHsDK7D5YxCxt+y9RiLUyO7SkAvLytX6/VnrM0sbSjpAgHydgvVOG7kkx6YBZzBt/meipF2DaMtgu8uZo29KlhQzF+sEjYh20F7T4G6DsIzv5ENKSzaToAaEuJw1J2TMJ+BBP4dZOr1O8E62lsanIiflrltc/wYxZJJx6aSGI+EGl4C0sSW62+sYJL34gWEehkGbEoSL8SOmKbunl8BBkO3NiXdjJO5fZuWQfIQOj2ArWA9qx7FHwhcH2Hrb7uZpm126K+sQ/GFgDsTMX+H24jHF41aF3Paj3INLdrpLpQ6cC/3u3WSVj78pZIXt0vOcvbr1L7r+lzwSIo/hJxWD0bCh/zN2cHESa7iwquhysfOP9cdl8JnH8uENDyoPX2EivYWVlbAC0Cefw1I=
  template:
    metadata:
      creationTimestamp: null
      labels:
        component: velero
      name: cloud-credentials
      namespace: velero
    type: Opaque
