apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  chart:
    spec:
      chart: immich
      version: 0.9.3
      sourceRef:
        kind: HelmRepository
        name: immich
  interval: 1h0m0s
  releaseName: immich
  targetNamespace: immich
  values:
    image:
      tag: v1.143.1
    useDeprecatedPostgresChart: true
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-data
    postgresql:
      enabled: true
    redis:
      enabled: true
    server:
      ingress:
        main:
          enabled: true
          annotations:
            gethomepage.dev/name: Immich
            gethomepage.dev/description: Photo galery
            gethomepage.dev/enabled: "true"
            gethomepage.dev/group: Photos
            gethomepage.dev/icon: immich.png
            gethomepage.dev/pod-selector: "app.kubernetes.io/instance=immich"
          hosts:
            - host: immich.totorinho.duckdns.org
              paths:
                - path: /
          tls: 
            - secretName: duckdns-wildcard-cert-totorinho.duckdns.org
              hosts:
                - immich.totorinho.duckdns.org
