apiVersion: apps/v1
kind: Deployment
metadata:
  name: maybe
  namespace: maybe
  labels:
    app.kubernetes.io/name: maybe
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: maybe
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: maybe
    spec:
      containers:
        - name: web
          image: "ghcr.io/maybe-finance/maybe:latest"
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          envFrom:
            - configMapRef:
                name: maybe-env
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: maybe-key
                  key: secret-key
          volumeMounts:
            - mountPath: /rails/storage
              name: storage
        - name: worker
          image: "ghcr.io/maybe-finance/maybe:latest"
          command: ["bundle", "exec", "sidekiq"]
          envFrom:
            - configMapRef:
                name: maybe-env
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: port
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-app
                  key: password
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: maybe-key
                  key: secret-key
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: maybe-app-storage
