apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maybe-app-storage
  namespace: maybe
  labels:
    app.kubernetes.io/name: maybe
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

