---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: maybe-key
  namespace: maybe
spec:
  encryptedData:
    secret-key: AgAhdl9shjzyrN1+AvGwiK9UrMvuUfFxmRmfzuFUXoB9nZ9UUELgEIQNvDrJiiOBR8jnQk/HGVin/vi5XXcvaHIfFTgz5p+BZKpPluVRgX86NCQ4IvNHSoiAG2JhjP+3ibkJz7DyJLXcongdiP9kVgD4bNMvK4KtlDfHyfcR6z1OEOubclXKIyDlgDSTkUo442H8wd4XG58Of627Z5+wKhwWTepULFLMRmhuIa+Q9nZ2qrReFGwzTWFqQ2Mx/7PS6WfxfLs8qWReYOcpXFI5KnL65Fwz7GBvrp9IqJ1aX509kLOBG8R4oZ3AwXfsQUzbDJ2ofFreUfC4UrPVbHg4FWrGIAvrCW8gtE5s+l4NqdQzUUb5700FNH8Pv5HdTltQpmqtfaet9fkVa/6ecHPnpafZcroCzishzNtYMbazO7L8SPAG+q5toAHD9r1b1mt2RG1BAHfkQiADLum9ShVDg3VxpB3j8X4OUU10C4qbeSCflRNZSkoMj0UsRTDbSd+yByxhhTQEFkLwofo1aNWnVNU+jfwo/Ob4THaQ3kmWD0pjDP/BZajwPLt0Ecxw/ti4YSBdPOOqb23TXzzG8P/aIclg6N+DHxYu21dqELRj35vX8w4YTm6itK4QvDgO4uVVgnUjkKNu0HkKK5W4mVXoMLCetydVEUkk9f8vjAJKdEUfXuYGbTuWLlslvsPeNCp9S5GvJPtGMNTkJt4OGB4xOhQ5X1HnY3r4zjYo5nyrpUJpVzSwCKmHE3kfY1i6gWRVu/J1JWuVipfiFCtOvyRZLgNJGRkVjcpr/Da1fIDl/CkSPgtr2M5nojKRWRixAsh9nuzVWB8yB1TEuo8qmkanjNfSKcqWCQZSxPQjJV4yXa9j9g==
  template:
    metadata:
      creationTimestamp: null
      name: maybe-key
      namespace: maybe
