apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data-local
  namespace: mealie
  labels:
    app.kubernetes.io/name: mealie
  annotations:
    volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
