apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: intel-device-plugin
  namespace: intel-device-plugin
spec:
  interval: 1h0m0s
  url: https://intel.github.io/helm-charts/
