apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: node-feature-discovery
  namespace: node-feature-discovery
spec:
  interval: 1h0m0s
  url: https://kubernetes-sigs.github.io/node-feature-discovery/charts
