apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-cluster
  namespace: wallabag
spec:
  instances: 3
  storage:
    size: 2Gi
  monitoring:
    enablePodMonitor: true
  enableSuperuserAccess: true
