apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
  labels:
    app.kubernetes.io/name: wallabag
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: wallabag
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wallabag
    spec:
      containers:
        - name: wallabag
          image: "wallabag/wallabag"
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: pdo_pgsql
            - name: SYMFONY__ENV__DATABASE_DRIVER_CLASS
              value: Wallabag\CoreBundle\Doctrine\DBAL\Driver\CustomPostgreSQLDriver
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: https://wallabag.totorinho.duckdns.org
            - name: SYMFONY__ENV__DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: postgresql-cluster-app
                  key: host
            - name: SYMFONY__ENV__DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: postgresql-cluster-app
                  key: port
            - name: SYMFONY__ENV__DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: postgresql-cluster-app
                  key: dbname
            - name: SYMFONY__ENV__DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-cluster-app
                  key: username
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-cluster-app
                  key: password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgresql-cluster-superuser
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-cluster-superuser
                  key: password

