apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  chart:
    spec:
      chart: home-assistant
      version: 0.2.83
      sourceRef:
        kind: HelmRepository
        name: home-assistant
  interval: 1h0m0s
  releaseName: home-assistant
  targetNamespace: home-assistant
  values:
    ingress:
      enabled: true
      annotations:
        gethomepage.dev/name: Home Assistant
        gethomepage.dev/description: Home devices manager
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Home
        gethomepage.dev/icon: home-assistant.png
        gethomepage.dev/pod-selector: "app.kubernetes.io/instance=home-assistant"
      hosts:
        - host: home-assistant.totorinho.duckdns.org
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls:
        - secretName: duckdns-wildcard-cert-totorinho.duckdns.org
          hosts:
            - home-assistant.totorinho.duckdns.org
    persistence:
      enabled: true
      storageClass: local-path
      accessMode: ReadWriteOnce
      size: 1Gi
    serviceMonitor:
      enabled: true
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.0.0.0/8
