apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 1h0m0s
  url: http://pajikos.github.io/home-assistant-helm-chart/
