apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent-config-local
  namespace: media
  labels:
    app: qbittorrent
  annotations:
    volumeType: local
spec:
  storageClassName: local-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
