apiVersion: apps/v1
kind: Deployment
metadata:
  name: glance
  namespace: glance
  labels:
    app.kubernetes.io/name: glance
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/name: glance
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glance
    spec:
      enableServiceLinks: true
      containers:
        - name: glance
          image: glanceapp/glance:v0.8.4
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /app/config/glance.yml
              name: glance-config
              subPath: glance.yml
      volumes:
        - name: glance-config
          configMap:
            name: glance
