apiVersion: v1
kind: Service
metadata:
  name: glance
  namespace: glance
  labels:
    app.kubernetes.io/name: glance
spec:
  selector:
    app.kubernetes.io/name: glance
  ports:
    - port: 8080
      targetPort: 8080
