apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: cloudnative-pg
  namespace: postgresql-operator-system
spec:
  chart:
    spec:
      chart: cloudnative-pg
      version: ">=0.22.0"
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg
  interval: 1h0m0s
  releaseName: cloudnative-pg
  targetNamespace: postgresql-operator-system
