apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cloudnative-pg
  namespace: postgresql-operator-system
spec:
  interval: 1h0m0s
  url: https://cloudnative-pg.github.io/charts
