apiVersion: v1
kind: ConfigMap
metadata:
  name: cert-manager-helm-chart-value-overrides
  namespace: cert-manager
data:
  values.yaml: |-
    installCRDs: true
    extraArgs:
      - --dns01-recursive-nameservers=1.1.1.1:53,9.9.9.9:53
      - --dns01-recursive-nameservers-only
    podDnsPolicy: None
    podDnsConfig:
      nameservers:
        - "1.1.1.1"
        - "9.9.9.9"
    serviceAccount:
      create: true
      name: "cert-manager-service-account"
