apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiori-data
  namespace: shiori
  labels:
    app.kubernetes.io/name: shiori
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

