apiVersion: apps/v1
kind: Deployment
metadata:
  name: zettelkasten-exporter
  namespace: monitoring
  labels:
    app.kubernetes.io/name: zettelkasten-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: zettelkasten-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zettelkasten-exporter
    spec:
      containers:
        - name: zettelkasten-exporter
          image: ghcr.io/luissimas/zettelkasten-exporter:0.3.2
          imagePullPolicy: Always
          env:
          - name: LOG_LEVEL
            value: INFO
          - name: IGNORE_FILES
            value: .git,.obsidian,.trash,.quartz,README.md
          - name: COLLECTION_INTERVAL
            value: 1h
          - name: ZETTELKASTEN_GIT_URL
            value: https://github.com/luissimas/vault
          - name: ZETTELKASTEN_GIT_BRANCH
            value: master
          - name: ZETTELKASTEN_GIT_TOKEN
            valueFrom:
              secretKeyRef:
                name: zettelkasten-exporter-env
                key: github-token
          - name: VICTORIAMETRICS_URL
            value: http://victoria-metrics-single-server:8428
