---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: zettelkasten-exporter
  namespace: monitoring
spec:
  type: oci
  interval: 5m0s
  url: oci://ghcr.io/luissimas/zettelkasten-exporter-chart
