apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: kube-system
spec:
  chart:
    spec:
      chart: headlamp
      version: 0.27.0
      sourceRef:
        kind: HelmRepository
        name: headlamp
  interval: 1h0m0s
  values:
    ingress:
      enabled: true
      ingressClassName: traefik
      hosts:
        - host: headlamp.totorinho.duckdns.org
          paths:
            - path: /
              type: ImplementationSpecific
      tls:
        - secretName: duckdns-wildcard-cert-totorinho.duckdns.org
          hosts:
            - headlamp.totorinho.duckdns.org
      annotations:
        gethomepage.dev/name: Headlamp UI
        gethomepage.dev/description: Kubernetes UI
        gethomepage.dev/enabled: "true"
        gethomepage.dev/group: Management
        gethomepage.dev/icon: kubernetes.png
        gethomepage.dev/pod-selector: "app.kubernetes.io/name=headlamp"
    config:
      pluginsDir: /build/plugins
    initContainers:
      - command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        name: headlamp-plugins
        volumeMounts:
          - mountPath: /build/plugins
            name: headlamp-plugins
    persistentVolumeClaim:
      accessModes:
        - ReadWriteOnce
      enabled: true
      size: 1Gi
    volumeMounts:
      - mountPath: /build/plugins
        name: headlamp-plugins
    volumes:
      - name: headlamp-plugins
        persistentVolumeClaim:
          claimName: headlamp
