apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octobot-tentacles
  namespace: octobot
  labels:
    app.kubernetes.io/name: octobot
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octobot-user
  namespace: octobot
  labels:
    app.kubernetes.io/name: octobot
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

