---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgBObUoWD7wcD1hXNaP9BizuPa2nN9wk8G3sYRkiX1PDj2lB8h/wWSMe3IbLmSIvzySBbTJye+MxAe+WeIST/fdqTDDmtkzTyqRMtr0SToWy7dMneDlaFzItIfy9MYTR5jbwnE2wa3/i0vuhuuqbZjxFfk9wqr/rVlLFuO77lO6A5bMFzU5YnnEDlecNe6fWc+TvGN8C7OFhJXPxgc7c86ejjIsb2juV4r77CClEEEwTNJV1bDGG9CtuKw1mJVazvXzaWaZ7LqkCUQxyw9s1c6Z4etiUqSOV78KZA161xbCBU9qMREGWh5a1pQ4SObnymcL92hgA+QdHJNhDviZMTWnS16TlblH6YGTpx3+8gNvvAnnBRFX8eJYsI3OzNS0TsdThRKDHocywIrHYCR4q5CcBeYxKzioufso8mTMDNFfSPno1G21Qwh8f1DXERs+6k511ZfiFY2+GSoJTccj+Enh2oO3y3MvnoR8yXMM5nv/H517Y9B3HSvCaOC4dY1x3INfy04rinVSjCaTGD6OaPDilXqEx87L0xROn+D6oAp84kJJpgOoDtDKZYGM1E+GfeZjmcujYHcPpru9fC0xRrJjTR+YJUtK4nZKxlm3ZP7BMtMJDhn/LadXW+Qs3VXtEEvY39tBZqvHWFqp2dpT10eWJLWndsmjCfWPKuU5IV7QFGC5LqYi9ZjaBFr8KDnKkocnWlgBsBpyfBvddwtjARDV1qxREsqbevRWm8Jy2vDCTKEzF6reNpRz6Puftj/iOrEAaF6UvzrMGADIlEYmBxCSHV16IT23q58GwMTnIiYvrrGJNjwigldMlbWWOW4kG2QxbGSmfTmlwKgYVTWWcSMX2TVOEWIgw5AYlJlGmVh0QHY4ZTztCdat5KsesXROdcg6mxlbgQ09Fr/YKInU=
  template:
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
