apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traggo-data
  namespace: traggo
  labels:
    app.kubernetes.io/name: traggo
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

