apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
  namespace: echo
spec:
  selector:
    matchLabels:
      app: echo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      containers:
        - name: echo-app
          image: hashicorp/http-echo
          args:
            - "-text=$(TEXT)"
          ports:
            - containerPort: 5678
          env:
            - name: TEXT
              valueFrom:
                secretKeyRef:
                  name: test-secret
                  key: sealed-value
---
apiVersion: v1
kind: Service
metadata:
  name: echo-svc
  namespace: echo
spec:
  selector:
    app: echo-app
  ports:
    - port: 5678
      targetPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: echo-ingress
  namespace: echo
spec:
  rules:
    - host: echo.totorinho.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: echo-svc
                port:
                  number: 5678
