apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: echo
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: volume
              mountPath: /data
      volumes:
        - name: volume
          persistentVolumeClaim:
            claimName: test-local-path-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: echo
spec:
  selector:
    app: nginx-app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: echo
spec:
  rules:
    - host: nginx.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nginx-svc
                port:
                  number: 80
