apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: webhook-duckdns
  namespace: cert-manager
spec:
  chart:
    spec:
      chart: ./charts/cert-manager-webhook-duckdns
      sourceRef:
        kind: GitRepository
        name: cert-manager-webhook-duckdns
      version: 1.4.x
  interval: 1h0m0s
  releaseName: webhook-duckdns
  targetNamespace: cert-manager
  values:
    groupName: totorinho.duckdns.org
    certManager:
      namespace: cert-manager
      serviceAccountName: cert-manager
    secret:
      existingSecret: true
      existingSecretName: duckdns-token-secret
    clusterIssuer:
      email: luissimas@protonmail.com
      staging:
        create: true
      production:
        create: true
